name: CI Pipeline for Memory Game

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test JPEG files for corruption
        run: |
          for file in $(find . -name '*.jpg'); do
            file "$file" || exit 1
          done

  build-memory:
    runs-on: self-hosted
    needs: test-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t eloiselbc/memory .

  push-memory:
    runs-on: self-hosted
    needs: build-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eloiselbc
          password: :@Azertyqsd82

      - name: Push Docker image to Docker Hub
        run: docker push eloiseLBC/memory

  deploy-memory:
    runs-on: self-hosted
    needs: push-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull eloiselbc/memory
            docker run -d -p 80:80 eloiselbc/memory
