name: CI Pipeline for Memory Game

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test JPEG files for corruption
        run: |
          for file in $(find . -name '*.jpg'); do
            file "$file" || exit 1
          done

  build-memory:
    runs-on: self-hosted
    needs: test-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/memory .

  push-memory:
    runs-on: self-hosted
    needs: build-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/memory

  deploy-memory:
    runs-on: self-hosted
    needs: push-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug secrets
        run: |
          echo "HOST: ${{ secrets.HOST }}"
          echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"

      - name: Deploy to Server using Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /chemin/vers/votre/projet  # Modifiez par le chemin du projet sur votre serveur
            docker-compose down            # Arrête les containers existants
            docker-compose pull            # Met à jour les images si nécessaire
            docker-compose up -d           # Lance les containers en arrière-plan
